services:
  # Main Tig application
  tig:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mount current directory for live code updates
    environment:
      - ENV=development
      - LOG_LEVEL=debug
    depends_on:
      - badger
      - cockroach

  # BadgerDB for local content storage
  badger:
    image: dgraph/standalone:latest
    ports:
      - "8000:8000"
      - "9080:9080"
    volumes:
      - badger_data:/dgraph
    environment:
      - BADGER_MODE=memory

  # CockroachDB for metadata
  cockroach:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"  # SQL port
      - "8081:8081"    # UI port
    command: start-single-node --insecure
    volumes:
      - cockroach_data:/cockroach/cockroach-data

volumes:
  badger_data:
  cockroach_data: